version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app/build/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/after_deploy.sh
      timeout: 300
      runas: root